name: C/C++ CI

on:
  push:
    branches: [ main, Assembler ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build